services:
  traefik:
    image: docker.io/traefik:v3.6 # {"magos": {"policy": "manual"}}
    container_name: traefik
    restart: unless-stopped
    env_file:
      - ../../secrets/.runtime/traefik.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command:
      - --api.dashboard=true
      - --api.insecure=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      
      # force HTTPS
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https

      - --providers.docker=true
      - --providers.docker.endpoint=unix:///run/podman/podman.sock
      - --providers.docker.exposedbydefault=false

      # --- Certificates ---
      - --certificatesresolvers.cloudflare.acme.dnschallenge=true
      - --certificatesresolvers.cloudflare.acme.dnsChallenge.propagation.delayBeforeChecks=300
      - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1:53
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.cloudflare.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.cloudflare.acme.storage=/letsencrypt/acme.json

      - --log.level=INFO
      - --accesslog=true
    ports:
      - "80:80"
      - "443:443"
      - "8081:8080"
    volumes:
      - /run/podman/podman.sock:/run/podman/podman.sock:ro
      - /data/traefik/letsencrypt:/letsencrypt
    networks:
      - singularity

networks:
  singularity:
    external: true
